/*
 * This source file was generated by the Gradle 'init' task
 */
package org.CodificacionHuffman.app;

import org.CodificacionHuffman.app.gui.*;

public class App {
    private static Principal objGUIPrincipal;

    public static void main(String[] args) {
        objGUIPrincipal = new Principal();
        objGUIPrincipal.runGUI();
        
        System.out.println("Run App!");
    }
}
